### ISSUE TITLE
ERROR: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by andrey-str** [nemirlev/zenexport#1]
Was trying to install from https://github.com/nemirlev/zenmoney-dashboard.
Copied .env file according to instruction, etc., but it failed on `docker-compose up` step with the following error message:

```bash
❯ docker-compose up -d
Pulling app (nemirlev/zenexport:latest)...
latest: Pulling from nemirlev/zenexport
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

I'm on Ubuntu 22.04.

Any idea how to fix it?

**Comment by nemirlev** [comment]
Hello,

Currently, the Docker image is built only for macOS, which is why you are encountering compatibility issues on your Ubuntu system.

Try Run `docker build -t IMAGE_NAME .` to build the image add change on docker-compose.

Alternatively, I will add a GitHub Actions workflow by tomorrow to automatically build Docker images for multiple platforms, including Linux AMD64. This update should resolve the issue.

**Comment by nemirlev** [comment]
@andrey-str try again, I update image

**Comment by andrey-str** [comment]
Thanks, this is working now!
